version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
        environment:
          PGHOST: localhost
          PGUSER: root
      - image: circleci/postgres:9.6

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: createdb collecshare_test
      - run: knex migrate:latest --env test
      - run: yarn test
